### ISSUE TITLE
Your work is great, when will the code be released?

### ISSUE THREAD

**Issue by Henkwu** [TencentYoutuResearch/Classification-SemiCLS#1]
The paper say that the code will be made publicly available after the paper is accepted.
Your work is great, when will the code be released?

**Comment by KaiWU5** [comment]
The code will release soon (within one week). Some TencentYouTu code publication processes need to go through.

**Comment by KaiWU5** [comment]
I have uploaded the code (other than Comatch+CCSSL because the code checking tool warning about high duplication with Comatch. We will solve that later). Any other questions, feel free to ask. # https://github.com/TencentYoutuResearch/Classification-SemiCLS/commit/5aaba39d869b1653cf79d76b18d8d0bc2ebee07d
