### ISSUE TITLE
STL10 results of fixmatch not correct

### ISSUE THREAD

**Issue by sailist** [TencentYoutuResearch/Classification-SemiCLS#3]
Thank you for your beautiful work! But there is a question: In the original [fixmatch paper](https://arxiv.org/pdf/2001.07685.pdf), the stl10 error rate is  5.17±0.63(94.93 accuracy), however the result on your paper is 65.38±0.42, are there any differences in your experiments?

**Comment by KaiWU5** [comment]
Thanks for kindly mentioning. In original Fixmatch and MixMatch, WRN-37-2 is written to be used for STL-10. But the way to implement WRN-37-2 is not like WRN-28-2 because 37 cannot be divided by 2. In https://github.com/google-research/fixmatch/issues/34, David said they even got number of parameters wrong for WRN-37-2.
So, to make experiments simple and consistent, we use Resnet-18 for STL10, the same in [Comatch paper](https://arxiv.org/abs/2011.11183)  as mentioned in our paper.
